OKnesset.strings = {
	hasBillsTitle 			: "הצעות חוק פרטיות שעברו קריאה טרומית",
	hasNoBillsTitle			: "אין הצעות חוק פרטיות שעברו קריאה טרומית",
	excuseForNoBills		: 'שרים בממשלה ויו"ר הכנסת אינם מגישים, ככלל, הצעות חוק פרטיות',
	partiesTitle	 		:'מפלגות',
	openBillTitle 			:'הצעת החוק תיפתח בדפדפן',
	openBillText			: 'לפתוח בדפדפן?',
	dialogOKCancel	 		: 'ביטול,אישור',
	downloadDataText	 	: 'מכשירך מחובר לרשת באמצעות חיבור סלולרי. הנתונים הנוכחיים מתאריך {0} והורדת הנתונים העדכניים בנפח של כ 1.5 מגה.',
	downloadDataTitle		: 'לעדכן נתונים מהאינטרנט?',
	errorOpenBill 			: 'לא ניתן לפתוח את הצעת החוק בדפדפן',
	openKnessetTitle		: 'כנסת פתוחה',
	back					: 'חזרה',
	cancel					: 'ביטול',
	dataDate				: 'הנתונים מעודכנים לתאריך {0}.',
	updateComplete			: "עדכון נתונים נעשה בהצלחה",
	oknessetName			: 'כנסת פתוחה',
	ministerIndicator		: "שר",
	knessetChairman			: "יושב ראש הכנסת",
	emailDialogTitle		: "שליחת משוב על האפליקציה",
	emailDialogBody			: "תודה שבחרתם לעזור לנו לשפר את האפליקציה 'כנסת פתוחה'! </br>שלחו מייל בנושא:",
	emailGeneral			: "משוב כללי",
	emailPartyList			: "משוב בנוגע למסך מפלגות",
	emailParty				: "משוב בנוגע למסך מפלגת {0}",
	emailMember				: 'משוב בנוגע למסך ח"כ {0}'
};

